spring:
  datasource:
    url: jdbc:postgresql://localhost/vk-internship
    username: postgres
    password: ruslan5099
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
